language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"
install:
  - pip install pipenv
  - pipenv install --dev
cache: pip
env:
  - PYTHONPATH=.
script:
  - pipenv run pytest
  - pipenv check
